export const GET_CLIENTS_REQUEST = "GET_CLIENTS_REQUEST";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_FAIL = "GET_CLIENTS_FAIL";
export const GET_CLIENTS_DETAIL_REQUEST = "GET_CLIENTS_DETAIL_REQUEST";
export const GET_CLIENTS_DETAIL_SUCCESS = "GET_CLIENTS_DETAIL_SUCCESS";
export const GET_CLIENTS_DETAIL_FAIL = "GET_CLIENTS_DETAIL_FAIL";
export const CREATE_CLIENTS_REQUEST = "CREATE_CLIENTS_REQUEST";
export const CREATE_CLIENTS_SUCCESS = "CREATE_CLIENTS_SUCCESS";
export const CREATE_CLIENTS_FAIL = "CREATE_CLIENTS_FAIL";
export const UPDATE_CLIENT_STATUS_REQUEST = "UPDATE_CLIENT_STATUS_REQUEST";
export const UPDATE_CLIENT_STATUS_SUCCESS = "UPDATE_CLIENT_STATUS_SUCCESS";
export const UPDATE_CLIENT_STATUS_FAIL = "UPDATE_CLIENT_STATUS_FAIL";
export const UPDATE_CLIENT_FEES_REQUEST = "UPDATE_CLIENT_FEES_REQUEST";
export const UPDATE_CLIENT_FEES_SUCCESS = "UPDATE_CLIENT_FEES_SUCCESS";
export const UPDATE_CLIENT_FEES_FAIL = "UPDATE_CLIENT_FEES_FAIL";
export const UPDATE_CLIENT_ADMISSION_REQUEST =
  "UPDATE_CLIENT_ADMISSION_REQUEST";
export const UPDATE_CLIENT_ADMISSION_SUCCESS =
  "UPDATE_CLIENT_ADMISSION_SUCCESS";
export const UPDATE_CLIENT_ADMISSION_FAIL = "UPDATE_CLIENT_ADMISSION_FAIL";
export const UPDATE_CLIENT_UNPAID_FEES_REQUEST =
  "UPDATE_CLIENT_UNPAID_FEES_REQUEST";
export const UPDATE_CLIENT_UNPAID_FEES_SUCCESS =
  "UPDATE_CLIENT_UNPAID_FEES_SUCCESS";
export const UPDATE_CLIENT_UNPAID_FEES_FAIL = "UPDATE_CLIENT_UNPAID_FEES_FAIL";
export const CLEAR_ALL_ERRORS = "CLEAR_ALL_ERRORS";
export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL";
export const EDIT_CLIENT_REQUEST = "EDIT_CLIENT_REQUEST";
export const EDIT_CLIENT_SUCCESS = "EDIT_CLIENT_SUCCESS";
export const EDIT_CLIENT_FAIL = "EDIT_CLIENT_FAIL";
