export const GET_ALL_REMINDER_REQUEST = "GET_ALL_REMINDER_REQUEST";
export const GET_ALL_REMINDER_SUCCESS = "GET_ALL_REMINDER_SUCCESS";
export const GET_ALL_REMINDER_FAIL = "GET_ALL_REMINDER_FAIL";
export const CREATE_REMINDER_REQUEST = "CREATE_REMINDER_REQUEST";
export const CREATE_REMINDER_SUCCESS = "CREATE_REMINDER_SUCCESS";
export const CREATE_REMINDER_FAIL = "CREATE_REMINDER_FAIL";